# Generated by Django 3.2.9 on 2021-11-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='review/movie/', verbose_name='映画ジャケット画像'),
        ),
    ]
