# Generated by Django 3.2.9 on 2021-11-24 02:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_movie_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('content', models.CharField(max_length=200, verbose_name='コメント本文')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.movie', verbose_name='対象映画')),
            ],
        ),
    ]
