# Generated by Django 3.2.9 on 2021-12-15 02:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリ名')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='映画説明'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(blank=True, null=True, verbose_name='映画の公開日'),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='review.category', verbose_name='カテゴリ'),
        ),
    ]
